name: "icloud-extension"
services:
  copilot:
    restart: always
    init: true
    build:
      context: ./copilot
    volumes:
      - ./copilot/public:/app/public
      - ./copilot/src:/app/src
      - ./copilot/dist:/app/dist