name: "icloud-extension"

services:
  copilot:
    restart: always
    init: true
    build:
      context: ./copilot+translate
      target: dev
    volumes:
      - ./copilot+translate/dist:/app/dist
      - ./copilot+translate/src:/app/src
      - ./copilot+translate/public:/app/public