name: "icloud-extension"

services:
  copilot:
    restart: always
    init: true
    build:
      context: ./copilot+translate
    volumes:
      - ./copilot+translate/chrome-extension:/app/chrome-extension
      - ./copilot+translate/pages:/app/pages
      - ./copilot+translate/bin:/app/bin