name: "icloud-extension"
services:
  copilot:
    restart: always
    init: true
    build:
      context: ./copilot+translate
    volumes:
      - ./copilot+translate/public:/app/public
      - ./copilot+translate/src:/app/src
      - ./copilot+translate/dist:/app/dist